name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Atau sesuaikan dengan branch utama Anda, 'master' atau 'main'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint and format files
        run: |
          npm run lint || true
          npm run format

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  # Folder yang akan di-deploy
          branch: gh-pages  # Branch tujuan untuk GitHub Pages
          clean: true  # Bersihkan branch tujuan sebelum di-deploy
